### ISSUE TITLE
Codeforces API

### ISSUE THREAD

**Issue by rexim** [gnull/cfparser#2]
Hi!

Nice script! :) Do you still develop it? Do you plan to use [Codeforces API](http://codeforces.com/api/help) instead of parsing in the future?

**Comment by gnull** [comment]
Hello!

I have been a bit busy for last few months, but the project is not dead. I'll continue development one day. ;) Neither submission nor samles fetching are supported by the API, so it is completely useless for us. Parsing html in lisp is evil, I will be happy to use API when better times come.

**Comment by rexim** [comment]
@gnull thanks for the response! :) Very well then. Let's wait for the better times. I close this issue for now.
